using System;

namespace err{
   class div{
      int result;
      
      div() {
         result = 0;
      }
      public void division(int num1, int num2) {
         try {
            result = num1 / num2;
         } catch (DivideByZeroException e) {
            Console.WriteLine("Exception caught: {0}", e);
         } finally {
            Console.WriteLine("Result: {0}", result);
         }
      }
      static void Main(string[] args) {
         div d = new div();
         d.division(25, 0);
         Console.ReadKey();
      }
   }
}